version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"
      - "44380:443"
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: 
      on-failure

  postgres:
    image: postgres:11-alpine
    container_name: fruits-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fruits-basket
    restart: always
    ports:
      - 15433:5432
    networks:
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres-data: