version: '3.4'

services:
  postgres:
    image: postgres:11-alpine
    container_name: fruits-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: fruits-basket
    restart: always
    ports:
      - 15433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  flyway:
    image: flyway/flyway:7
    restart: on-failure
    command: -url=jdbc:postgresql://postgres:5432/fruits-basket -schemas=public -user=postgres -password=docker migrate
    environment:
      - FLYWAY_EDITION=community
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres-data:
