CREATE TABLE IF NOT EXISTS public."User" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Email" text NULL,
	"Senha" text NULL,
	CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Fruit" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"Name" varchar(250) NOT NULL,
	"Description" varchar(500) NULL,
	"AvailableQuantity" int4 NOT NULL,
	"Picture" bytea NOT NULL,
	"Price" numeric(10,2) NOT NULL,
	CONSTRAINT "PK_Fruit" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Store" (
	"Id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"FruitId" int4 NOT NULL,
	"Quantity" int4 NOT NULL,
	"TotalValue" numeric(10,2) NOT NULL,
	CONSTRAINT "PK_Store" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Store_Fruit_FruitId" FOREIGN KEY ("FruitId") REFERENCES "Fruit"("Id") ON DELETE CASCADE
);
